import socket
import uuid
import random
from secure_vault import SecureVault
from util import covert_str_list_to_int_list, xor, encrypt, decrypt

random.seed(42)

def main():
  SERVER_HOST = '127.0.0.1'
  SERVER_PORT = 12345

  ID = 16 #uuid.uuid4()
  SESSION_ID = 1

  with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as client_socket:
    client_socket.connect((SERVER_HOST, SERVER_PORT))

    sv = SecureVault()
    K = sv.generate_secure_vault()

    # Invia i dati al server
    M1 = str(ID) + "#" + str(SESSION_ID)
    client_socket.sendall(str(M1).encode())
    #------------------------------------------------

    data_received = client_socket.recv(1024)

    M2 = data_received.decode()
    print(f"M2: {M2}")
    C1 = covert_str_list_to_int_list(M2.split("#")[0])
    print(f"C1: {C1}")
    r1 = int(M2.split("#")[1])

    # First, it generates a temporary key k1 of size m bits by performing 
    # XOR operation on all the keys whose indices are in C1.
    p = len(C1)
    k1 = []
    for i in range(p):
      if (i == 0):
        k1 = K[C1[i]]
      else:
        k1 = xor(k1, K[C1[i]])

    print(f"k1: {k1}")

    # The IoT device creates the response for the challenge by performing shared key 
    # encryption on r1 || t1 using k1 as the encryption key.
    # Here, t1 is a random number generated by the IoT device, which is further used to generate 
    # a session key t.
    t1 = random.randint(0, 255)
    # perform shared key encryption on r1 || t1 using k1 as the encryption key
    challenge_response = encrypt(bytes(k1), bytes([r1, t1]))
 


if __name__ == "__main__":
  sv = SecureVault()
  sv.generate_secure_vault()
  #main()
