import socket
import secure_vault
from socket_util import SocketUtil
from util import (
    list_xor,
    xor,
    decrypt,
    generate_challenge,
    generate_session_key,
    unpack_M4
  )

def main():
  SERVER_HOST = '127.0.0.1'
  SERVER_PORT = 12345

  ID = 16 #uuid.uuid4()
  SESSION_ID = 1

  with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as client_socket:
    client_socket.connect((SERVER_HOST, SERVER_PORT))

    socket_util = SocketUtil(client_socket)

    K = secure_vault.load_secure_vault()

    # Invia i dati al server
    socket_util.sendM1(ID, SESSION_ID)
    #------------------------------------------------
    C1, r1 = socket_util.receiveM2()

    # First, it generates a temporary key k1 of size m bits by performing 
    # XOR operation on all the keys whose indices are in C1.
    k1 = list_xor([K[i] for i in C1])

    # The IoT device creates the response for the challenge by performing shared key 
    # encryption on r1 || t1 using k1 as the encryption key.
    # Here, t1 is a random number generated by the IoT device, which is further used to generate 
    # a session key t.
    t1 = generate_session_key()
    # perform shared key encryption on r1 || t1 using k1 as the encryption key
    C2, r2 = generate_challenge(secure_vault.N)
    socket_util.sendM3(k1, r1, t1, C2, r2)
    #------------------------------------------------
    M4 = socket_util.receiveM4()
    k2 = list_xor([K[i] for i in C2])
    xor_result = xor(k2, t1)
    payload = decrypt(xor_result, M4).decode()

    r2_server, t2 = unpack_M4(payload)

    if (r2_server != r2):
      print("Errore: r2 non corrisponde")
      return
    T = xor(t1, t2)

    #------------------------------------------------
    msg = socket_util.receiveMessageEncrypted(T)
    print(f"Msg: {msg.decode()}")
    socket_util.sendMessageEncrypted(T, b"Hello from the client!")


if __name__ == "__main__":
  #secure_vault.regen_secure_vault()
  main()
